name: 'AsciiDoctor Action'
description: 'Build site from AsciiDoc with AsciiDoctor'
author: 'Dmitry Rakovets'

inputs:
  command:
    description: 'Command for build'
    required: true
    default: "asciidoctor --backend html5 --source-dir . --destination-dir ./site '**/*.adoc'; cp -R ./assets ./site"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
