name: 'AsciiDoctor Action'
description: 'Build site from AsciiDoc with AsciiDoctor'
author: 'Dmitry Rakovets'

inputs:
  command:
    description: 'Command for build'
    required: true
    default: 'asciidoctor  --destination-dir . --backend html5 --source-dir **/*.adoc'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
